### ISSUE TITLE
3.4 [FRONTEND]Desenvolver o JS para dar a iteratividade e dinamismo para o carrossel.

### ISSUE THREAD

**Issue by wcarestini** [Squad-08/curtas.tv#11]
O carrossel já está praticamente todo feito, mas eu encontrei um erro com os botões que, ao clicar, o código quebra (crash). Tenho que solucionar isso.

**Comment by matheusleo** [comment]
Falta apenas corrigir uns pequenos bugs que aconteceram quando eu implementei o código,
